### ISSUE TITLE
RoR group project: set up Kanban board

### ISSUE THREAD

**Issue by keroloussamy** [ShadyShawkat/RoR-Recipe-App#19]
We have created our Kanban board, here is our [project](https://github.com/ShadyShawkat/RoR-Recipe-App/projects/1)

Team member 1: @keroloussamy 
Team member 2: @ShadyShawkat

**Comment by elyor-doniyorov** [comment]
Hi @keroloussamy and @ShadyShawkat, 

In my opinion, your Kanban board project is ready to use!  There is nothing else to say other than... well done :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
